---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04

suites:
  - name: run
    run_list:
      - recipe[java::default]
      - recipe[cassandra::default]
      - recipe[cassandra::configure]
      - recipe[cassandra::start]
    attributes:
      java:
        jdk_version: "8"
      cloudify:
        runtime_properties: {}

  - name: config
    run_list:
      - recipe[java::default]
      - recipe[cassandra::default]
      - recipe[cassandra::configure]
    attributes:
      java:
        jdk_version: "8"
      cloudify:
        runtime_properties:
          host_ip: 123.135.147.159
          seeds:
            - 111.11.1.123
            - 111.11.1.124
