---
suites:
  - name: run
    run_list:
      - recipe[java::default]
      - recipe[cassandra::default]
      - recipe[cassandra::configure]
      - recipe[cassandra::start]
    attributes:
      java: &java_attrs
        jdk_version: "8"
        install_flavor: openjdk
      cloudify:
        runtime_properties: {}
        properties:
          configuration: {}

  - name: config
    run_list:
      - recipe[java::default]
      - recipe[cassandra::default]
      - recipe[cassandra::configure]
    attributes:
      java: *java_attrs
      cloudify:
        runtime_properties:
          host_ip: 123.135.147.159
          seeds:
            - 111.11.1.123
            - 111.11.1.124
        properties:
          configuration:
            conf_1: string_value
            conf_2: 123
            conf_3:
              this: is
              nested: dict
              with:
                - array
                - of
                - strings
            # Next property should be overriden by cookbook, since rpc_address
            # should not be altered by user.
          listen_address: 43.21.654.32
