---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04

suites:
  - name: storm
    run_list:
      - recipe[dice_common::host]
      - recipe[apt::default]
      - recipe[dmon_agent::mock_dmon]
      - recipe[dmon_agent::default]
      - recipe[dmon_agent::collectd]
      - recipe[dmon_agent::storm]
    attributes:
      cloudify:
        properties:
          monitoring:
            enabled: true
      dmon_agent:
        dmon:
          ip: '127.0.0.1'
        logstash:
          ip: '10.211.55.100'

  - name: spark
    run_list:
      - recipe[dice_common::host]
      - recipe[apt::default]
      - recipe[dmon_agent::mock_dmon]
      - recipe[dmon_agent::default]
      - recipe[dmon_agent::collectd]
      - recipe[dmon_agent::spark]
    attributes:
      cloudify:
        properties:
          monitoring:
            enabled: true
      spark:
        spark-env:
          SPARK_CONF_DIR: /tmp
      dmon_agent:
        dmon:
          ip: '127.0.0.1'
        logstash:
          ip: '10.211.55.100'
