---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04

suites:
  - name: storm
    run_list:
      - recipe[apt::default]
      - recipe[dice-common::host]
      - recipe[dmon_agent::default]
      - recipe[dmon_agent::collectd]
      - recipe[dmon_agent::storm]
    attributes:
      dmon_agent:
        node_name: 'storm_agent'
        dmon:
          ip: '10.211.55.100' 
          port: '5001'
        logstash:
          ip: '10.211.55.100' 
          udp_port: '25826'
  
  - name: spark
    run_list:
      - recipe[apt::default]
      - recipe[dice-common::host]
      - recipe[dmon_agent::default]
      - recipe[dmon_agent::collectd]
      - recipe[dmon_agent::spark]
    attributes:
      dmon_agent:
        node_name: 'spark_agent'
        dmon:
          ip: '10.211.55.100' 
          port: '5001'
        logstash:
          ip: '10.211.55.100' 
          udp_port: '25826'
