---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04

suites:
  - name: storm
    driver:
      network:
        - ["private_network", {ip: "10.211.55.110"}]
    run_list:
      - recipe[apt::default]
      - recipe[dice-common::host]
      - recipe[dmon_agent::mock_dmon]
      - recipe[dmon_agent::default]
      - recipe[dmon_agent::collectd]
      - recipe[dmon_agent::storm]
    attributes:
      dmon_agent:
        node_ip: "10.211.55.110"
        dmon:
          ip: '127.0.0.1' 
        logstash:
          ip: '10.211.55.100' 
  
  - name: spark
    driver:
      network:
        - ["private_network", {ip: "10.211.55.111"}]
    run_list:
      - recipe[apt::default]
      - recipe[dice-common::host]
      - recipe[dmon_agent::mock_dmon]
      - recipe[dmon_agent::default]
      - recipe[dmon_agent::collectd]
      - recipe[dmon_agent::spark]
    attributes:
      dmon_agent:
        node_ip: "10.211.55.111"
        dmon:
          ip: '127.0.0.1' 
        logstash:
          ip: '10.211.55.100'
