---
suites:
  - name: storm
    excludes:
      - ubuntu-16.04
    run_list:
      - recipe[dice_common::host]
      - recipe[apt::default]
      - recipe[dmon_agent::mock_dmon]
      - recipe[dmon_agent::default]
      - recipe[dmon_agent::collectd]
      - recipe[dmon_agent::storm]
      - recipe[dmon_agent::start]
    attributes:
      storm:
        log_dir: /usr/share/storm/logs
      cloudify: &cfy_config
        node_id: sample_id
        deployment_id: sample_id
        properties:
          monitoring:
            enabled: true
            dmon_address: 127.0.0.1:5001
            logstash_lumberjack_address: 10.211.55.100:5000
            logstash_lumberjack_crt: crt
            logstash_graphite_address: 10.211.55.100:5002
            logstash_udp_address: 10.211.55.100:25826
            roles: []

  - name: spark
    excludes:
      - ubuntu-16.04
    run_list:
      - recipe[dice_common::host]
      - recipe[apt::default]
      - recipe[dmon_agent::mock_dmon]
      - recipe[dmon_agent::default]
      - recipe[dmon_agent::collectd]
      - recipe[dmon_agent::spark]
    attributes:
      cloudify: *cfy_config
      spark:
        spark-env:
          SPARK_CONF_DIR: /tmp

  # This one is named hadoop because logstash forwarder is used when
  # monitoring hadoop cluster. When we have actual recipe for hadoop, this can
  # be simply updated a bit.
  - name: hadoop
    excludes:
      - ubuntu-16.04
    run_list:
      - recipe[dice_common::host]
      - recipe[apt::default]
      - recipe[dmon_agent::mock_dmon]
      - recipe[dmon_agent::default]
      - recipe[dmon_agent::lsf]
    attributes:
      cloudify:
        node_id: sample_id
        deployment_id: sample_id
        properties:
          monitoring:
            enabled: true
            dmon_address: 127.0.0.1:5001
            logstash_lumberjack_address: 10.211.55.100:5000
            logstash_lumberjack_crt: crt
            logstash_graphite_address: 10.211.55.100:5002
            logstash_udp_address: 10.211.55.100:25826
            roles:
              - role_1
              - role_2

  - name: cassandra
    excludes:
      - ubuntu-16.04
    run_list:
      - recipe[dice_common::host]
      - recipe[apt::default]
      - recipe[dmon_agent::mock_dmon]
      - recipe[dmon_agent::default]
      - recipe[dmon_agent::collectd]
      - recipe[dmon_agent::cassandra]
    attributes:
      cloudify: *cfy_config

  - name: node_removal
    run_list:
      - recipe[dice_common::host]
      - recipe[dmon_agent::mock_dmon]
      - recipe[dmon_agent::remove_node]
    attributes:
      cloudify: *cfy_config
#
#  - name: mongo
#    run_list:
#      - recipe[apt::default]
#      - recipe[dice_common::host]
#      - recipe[mongodb::default]
#      - recipe[mongodb::configure]
#      - recipe[mongodb::start]
#      - recipe[dmon_agent::mock_dmon]
#      - recipe[dmon_agent::default]
#      - recipe[dmon_agent::collectd]
#      - recipe[dmon_agent::pymongo]
#      - recipe[dmon_agent::mongo]
#    attributes:
#      cloudify: *cfy_config
