---
suites:

  - name: server
    run_list:
      - recipe[apt::default]
      - recipe[dice_common::host]
      - recipe[docker::default]
      - recipe[docker::configure]
      - recipe[docker::start]
    attributes:
      cloudify:
        node_id: sample_node_id
        node_name: test_name
        deployment_id: sample_deploy_id
        properties: {}
        runtime_properties: {}
