---
suites:
  - name: namenode
    excludes:
      - ubuntu-16.04
    run_list:
      - recipe[dice_common::host]
      - recipe[apt::default]
      - recipe[java::default]
      - recipe[hadoop::default]
      - recipe[hadoop::hdfs_configure]
      - recipe[hadoop::namenode_configure]
      - recipe[hadoop::namenode_start]
    attributes:
      java: &java_attrs
        jdk_version: "8"
        install_flavor: openjdk
      cloudify:
        node_id: sample_node_id
        deployment_id: sample_deploy_id
        properties: {}
        runtime_properties: {}

  - name: datanode
    excludes:
      - ubuntu-16.04
    run_list:
      - recipe[dice_common::host]
      - recipe[apt::default]
      - recipe[java::default]
      - recipe[hadoop::default]
      - recipe[hadoop::hdfs_configure]
      - recipe[hadoop::datanode_configure]
      - recipe[hadoop::datanode_start]
    attributes:
      java: *java_attrs
      cloudify:
        node_id: sample_node_id
        deployment_id: sample_deploy_id
        properties: {}
        runtime_properties:
          namenode_addr: namenode-ubuntu-1404.node.consul

  - name: resourcemanager
    excludes:
      - ubuntu-16.04
    run_list:
      - recipe[dice_common::host]
      - recipe[apt::default]
      - recipe[java::default]
      - recipe[hadoop::default]
      - recipe[hadoop::yarn_configure]
      # Next recipe requires functioning name node, so we skip it here
      #- recipe[hadoop::resourcemanager_configure]
      - recipe[hadoop::resourcemanager_start]
    attributes:
      java: *java_attrs
      cloudify:
        node_id: sample_node_id
        deployment_id: sample_deploy_id
        properties: {}
        runtime_properties:
          namenode_addr: namenode-ubuntu-1404.node.consul

  - name: nodemanager
    excludes:
      - ubuntu-16.04
    run_list:
      - recipe[dice_common::host]
      - recipe[apt::default]
      - recipe[java::default]
      - recipe[hadoop::default]
      - recipe[hadoop::yarn_configure]
      - recipe[hadoop::nodemanager_configure]
      - recipe[hadoop::nodemanager_start]
    attributes:
      java: *java_attrs
      cloudify:
        node_id: sample_node_id
        deployment_id: sample_deploy_id
        properties: {}
        runtime_properties:
          namenode_addr: namenode-ubuntu-1404.node.consul
          resourcemanager_addr: resourcemanager-ubuntu-1404.node.consul
