---
suites:
  - name: master-16
    excludes:
      - ubuntu-16.04
    run_list:
      - recipe[dice_common::host]
      - recipe[apt::default]
      - recipe[java::default]
      - recipe[spark::default]
      - recipe[spark::configure]
      - recipe[spark::start]
    attributes:
      java: &java_attrs
        jdk_version: "8"
        install_flavor: openjdk
      spark:
        type: master
        version: "1.6"
      cloudify:
        node_id: sample_node_id
        deployment_id: sample_deploy_id
        properties:
          configuration: {}
        runtime_properties: {}

  - name: master-20
    excludes:
      - ubuntu-16.04
    run_list:
      - recipe[dice_common::host]
      - recipe[apt::default]
      - recipe[java::default]
      - recipe[spark::default]
      - recipe[spark::configure]
      - recipe[spark::start]
    attributes:
      java: *java_attrs
      spark:
        type: master
        version: "2.0"
      cloudify:
        node_id: sample_node_id
        deployment_id: sample_deploy_id
        properties:
          configuration: {}
        runtime_properties: {}

  - name: worker-16
    excludes:
      - ubuntu-16.04
    run_list:
      - recipe[dice_common::host]
      - recipe[apt::default]
      - recipe[java::default]
      - recipe[spark::default]
      - recipe[spark::configure]
    attributes:
      java: *java_attrs
      spark:
        type: worker
        version: "1.6"
      cloudify:
        node_id: sample_node_id
        deployment_id: sample_deploy_id
        properties:
          configuration: {}
        runtime_properties:
          master_ip: 172.28.128.8

  - name: worker-20
    excludes:
      - ubuntu-16.04
    run_list:
      - recipe[dice_common::host]
      - recipe[apt::default]
      - recipe[java::default]
      - recipe[spark::default]
      - recipe[spark::configure]
    attributes:
      java: *java_attrs
      spark:
        type: worker
        version: "2.0"
      cloudify:
        node_id: sample_node_id
        deployment_id: sample_deploy_id
        properties:
          configuration: {}
        runtime_properties:
          master_ip: 172.28.128.9
