---
driver:
  name: vagrant
  network:
    - ["private_network", {type: "dhcp"}]
  customize:
    memory: 2048

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04

suites:
  - name: master-16
    run_list:
      - recipe[dice_common::host]
      - recipe[apt::default]
      - recipe[java::default]
      - recipe[spark::default]
      - recipe[spark::configure]
      - recipe[spark::start]
    attributes:
      spark:
        type: master
        version: "1.6"
      cloudify:
        properties:
          configuration: {}
        runtime_properties: {}

  - name: master-20
    run_list:
      - recipe[dice_common::host]
      - recipe[apt::default]
      - recipe[java::default]
      - recipe[spark::default]
      - recipe[spark::configure]
      - recipe[spark::start]
    attributes:
      spark:
        type: master
        version: "2.0"
      cloudify:
        properties:
          configuration: {}
        runtime_properties: {}

  - name: worker-16
    run_list:
      - recipe[dice_common::host]
      - recipe[apt::default]
      - recipe[java::default]
      - recipe[spark::default]
      - recipe[spark::configure]
      - recipe[spark::start]
    attributes:
      spark:
        type: worker
        version: "1.6"
      cloudify:
        properties:
          configuration: {}
        runtime_properties:
          master_ip: 172.28.128.8

  - name: worker-20
    run_list:
      - recipe[dice_common::host]
      - recipe[apt::default]
      - recipe[java::default]
      - recipe[spark::default]
      - recipe[spark::configure]
      - recipe[spark::start]
    attributes:
      spark:
        type: worker
        version: "2.0"
      cloudify:
        properties:
          configuration: {}
        runtime_properties:
          master_ip: 172.28.128.9
