---
driver:
  name: vagrant
  customize:
    memory: 2048
    cpus: 2

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04

suites:
  - name: elk
    run_list:
      - recipe[apt::default]
      - recipe[git::default]
      - recipe[java::default]
      - recipe[dmon::default]
      - recipe[dmon::elasticsearch]
      - recipe[dmon::kibana]
      - recipe[dmon::logstash]
      
