---
driver:
  name: vagrant
  customize:
    memory: 4096
    cpus: 4

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04

suites:
  - name: elk
    run_list:
      - recipe[apt::default]
      - recipe[git::default]
      - recipe[java::default]
      - recipe[dmon::default]
      - recipe[dmon::elk]
      - recipe[dmon::elk_conf]
