---
driver:
  name: vagrant
  network:
    - ["private_network", {ip: "10.211.55.100"}]
  customize:
    memory: 4096
    cpus: 4

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[apt::default]
      - recipe[git::default]
      - recipe[dmon::default]
    attributes:
