---
driver:
  name: vagrant
  customize:
    memory: 2048
    cpus: 2
  network:
    - ["forwarded_port", {guest: 5601, host: 5601}]
    - ["forwarded_port", {guest: 5001, host: 5001}]

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04

suites:
  - name: elk
    run_list:
      - recipe[apt::default]
      - recipe[java::default]
      - recipe[dmon::default]
      - recipe[dmon::elasticsearch]
      - recipe[dmon::kibana]
      - recipe[dmon::logstash]
    attributes:
      java: &java_attrs
        jdk_version: "8"
        install_flavor: openjdk
      cloudify:
        runtime_properties: {}
        properties:
          configuration: {}
