---
driver:
  name: vagrant
  customize:
    memory: 2048

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04

suites:

  - name: kafka
    run_list:
      - recipe[dice_common::host]
      - recipe[apt::default]
      - recipe[java::default]
      - recipe[kafka::default]
      - recipe[kafka::configure]
      #- recipe[kafka::start]  # This is left here on purpose to demo real use
    attributes:
      java:
        jdk_version: "8"
      cloudify:
        properties:
          configuration: {}
        runtime_properties:
          zookeeper_quorum:
            - localhost
