---
suites:

  - name: kafka
    excludes:
      - ubuntu-16.04
    run_list:
      - recipe[dice_common::host]
      - recipe[apt::default]
      - recipe[java::default]
      - recipe[kafka::default]
      - recipe[kafka::configure]
      #- recipe[kafka::start]  # This is left here on purpose to demo real use
    attributes:
      java:
        jdk_version: "8"
        install_flavor: openjdk
      cloudify:
        node_id: sample_node_id
        deployment_id: sample_deploy_id
        properties:
          configuration: {}
        runtime_properties:
          zookeeper_quorum:
            - localhost
