---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04

suites:
  - name: dice-ci-http
    run_list:
      - recipe[apt::default]
      - recipe[java::default]
      - recipe[dice_continuous_integration::default]
      - recipe[dice_continuous_integration::dice-qt]
    attributes:
      java: &java_attrs
        jdk_version: "8"
        install_flavor: openjdk
