---
suites:
  - name: dice-ci-http
    excludes:
      - ubuntu-16.04
    run_list:
      - recipe[apt::default]
      - recipe[java::default]
      - recipe[dice_continuous_integration::default]
      - recipe[dice_continuous_integration::dice-qt]
    attributes:
      java: &java_attrs
        jdk_version: "8"
        install_flavor: openjdk
