---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04

suites:
  - name: nimbus
    run_list:
      - recipe[storm-cluster::common]
      - recipe[storm-cluster::configure]
      - recipe[storm-cluster::start_nimbus]
      - recipe[storm-cluster::start_supervisor]
    attributes:
      java:
        jdk_version: "7"
      cloudify:
        properties:
          configuration:
            test_config_1: value_1
            test_config_2: value_2
        runtime_properties:
          zookeeper_quorum:
            - 123.231.45.66
            - 123.231.45.67
          storm_nimbus_ip: 123.231.45.68

  - name: storm
    run_list:
      - recipe[storm-cluster::common]
      - recipe[storm-cluster::configure]
      - recipe[storm-cluster::start_supervisor]
    attributes:
      java:
        jdk_version: "7"
      storm:
        storm_yaml:
          nimbus.seeds:
            - 543.210.65.43
          storm.zookeeper.servers:
            - a.b.c.d
            - e.f.g.h
