---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[apt::default]
      - recipe[dice_common::host]
      - recipe[dice_deployment_service::default]
      - recipe[dice_common::consul_common]
      - recipe[dice_common::consul_server]
    attributes:
      cloudify:
        node_id: sample_node_id
        deployment_id: sample_deploy_id
        runtime_properties: {}
        properties:
          ssh_key: abs
          debug_mode: true
          sources: https://github.com/dice-project/DICE-Deployment-Service/archive/develop.tar.gz
          manager: 1.2.3.4
          manager_user: tadej
          manager_pass: passw
          superuser_username: xuser
          superuser_password: xpass
          superuser_email: xmail
          no_celery_workers: 5
